apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-trace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-trace
  template:
    metadata:
      labels:
        app: nginx-trace
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
